ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/urls.py
from django.urls import path
from django.conf import settings
from . import views
from .views import login_view, register_user
from django.contrib.auth.views import LogoutView

urlpatterns = [
	#Leave as empty string for base url
	path('', views.store, name="store"),
	path('add/<str:pk>', views.add, name = "add"),
    path('add2/<str:pk>', views.add2, name = "add2"),
    path('add-product/<str:pk>', views.add_product, name = "add-product"),
	path('remove/<str:pk>', views.remove, name = "remove"),
	path('view/<str:pk>', views.view, name = "view"),
	path('cart/', views.cart, name="cart"),
	# path('checkout/', views.checkout, name="checkout"),
	path('place-order/', views.place_order, name="place-order"),
	path('enquiry/', views.enquiry, name="enquiry"),
	path('search/', views.search, name="search"),
	path('login/', login_view, name="login"),
   	path('register/', register_user, name="register"),
  	path("logout/", LogoutView.as_view(), name="logout"),
  	path('update/', views.update, name="update"),
	# path('update_item/', views.updateItem, name="update_item"),
	# path('process_order/', views.processOrder, name="process_order"),
	path('about_us/', views.about, name="about"),
	path('success/', views.successfulOrder, name="success"),
	path('addImage/', views.addImage, name='add_image'),
	path('addImageUpdate/<str:pk>', views.addImageUpdate, name='add_image_update'),
	path('jewellery/', views.jewellery, name = "jewellery"),

	path('ajax/enquiry/', views.ajax_enquiry, name = "ajax-enquiry"),
	path('ajax/cart/', views.ajax_cart, name = "ajax-cart"),

	path('activate-user/<pk>/', views.activate_user, name='activate-user')
]

store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


SHAPE_CHOICES = [
	('OTHER', 'OTHER'),
	('RD', 'Round'),#
	('AS', 'Asscher'),#
	('CU', 'Cushion'),#
	('EC', 'Emerald'),#
	('HS', 'Heart'),#
	('MQ', 'Marquise'),#
	('OV', 'Oval'),#
	('PR', 'Princess'),#
	('PS', 'Pear Shape'),#
	('RA', 'Radiant'),#
]

PSEUDO_SHAPE_CHOICES = [
    ('RD', 'Round'),#
	('BU', 'BU1'),
	('CU', 'Cushion'),#
	('EC', 'Emerald'),#
	('EU', 'EU1'),
	('HS', 'Heart'),#
	('MQ', 'Marquise'),#
	('OV', 'Oval'),#
	('OM', 'OM1'),
	('PR', 'Princess'),#
	('PS', 'Pear Shape'),#
	('RA', 'Radiant'),#
	('RD', 'Round'),#
	('AS', 'Asscher'),#
	('STB', 'STB1'),
	('TB', 'TB1'),
	('TR', 'TR1'),
]

x = [p[0] for p in SHAPE_CHOICES]

CLARITY_CHOICES = [
	('FL', 'FL'),
	('IF', 'IF'),
	('VVS1', 'VVS1'),
	('VVS2', 'VVS2'),
	('VS1', 'VS1'),
	('VS2', 'VS2'),
	('SI1', 'SI1'),
	('SI2', 'SI2'),
	('SI3', 'SI3'),
	('I1', 'I1'),
	('I2', 'I2'),
]

COLOR_CHOICES = [
	('D', 'D'),
	('E', 'E'),
	('F', 'F'),
	('G', 'G'),
	('H', 'H'),
	('I', 'I'),
	('J', 'J'),
	('K', 'K'),
	('L', 'L'),
	('M', 'M'),
	('N', 'N'),
]
FLOUROSCENE_CHOICES = [
    ('N', 'NONE'),
	('F', 'FAINT'),
	('M', 'MEDIUM'),
	('S', 'STRONG'),
	('VS','VERY STRONG')
]


LAB_CHOICES = [
	('GIA', 'GIA'),
	('EGL USA', 'EGL USA'),
	('OWN', 'Non-Certified')
]

CUT_CHOICES = [
	('EX', 'EX'),
	('VG', 'VG'),
	('G','GD'),
	('F', 'FR'),
]
SYM_CHOICES = [
	('X', 'EX'),
	('VG', 'VG'),
	('G', 'GD'),
	('F', 'FR'),
]
POL_CHOICES = [
	('EX', 'EX'),
	('VG', 'VG'),
	('G', 'GD'),
	('F', 'FR'),
]

class Customer(models.Model):
	user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
	fname = models.CharField(max_length=200, null=False, blank = False)
	lname = models.CharField(max_length=200, null=False, blank = False)
	company_name = models.CharField(max_length=200, null=False, blank = False)
	email = models.EmailField(max_length=100,null=False, blank=False, default='Spl@ymail.com')	
	mobile_no = models.CharField(max_length = 15, null = True, blank = True)

	

	def __str__(self):
		return self.user.username

"""
def create_customer(sender, instance, created, **kwargs):
	if created:
		profile, created = Customer.objects.get_or_create(user = instance)

post_save.connect(create_customer, sender = User)
"""

class Product(models.Model):

	name = models.CharField(max_length=200, null = True, blank = True, default = "-")
	lot_no = models.CharField(primary_key = True, max_length = 30)
	shape = models.CharField(max_length = 20, choices = SHAPE_CHOICES)
	pseudo_shape = models.CharField(max_length = 20, choices = PSEUDO_SHAPE_CHOICES, default = "OTHER")
	carat = models.FloatField(null = True, blank = True)
	stone = models.IntegerField(null = True, blank = True) # Quantity
	color = models.CharField(max_length = 25, choices = COLOR_CHOICES, default = "D")
	clarity = models.CharField(max_length = 25, choices = CLARITY_CHOICES, default = "FL")
	measurement = models.CharField(max_length = 50, null = True, blank = True)
	dept = models.FloatField(null = True, blank = True)
	tbl = models.IntegerField(null = True, blank = True)
	cut = models.CharField(max_length = 100,choices=CUT_CHOICES, null = True, blank = True, default = "-")
	pol = models.CharField(max_length = 10,choices=POL_CHOICES, null = True, blank = True, default = "-")
	sym = models.CharField(max_length = 10,choices=SYM_CHOICES, null = True, blank = True, default = "-")
	fl = models.CharField(max_length = 10,choices=FLOUROSCENE_CHOICES, null = True, blank = True, default = "-")
	cul = models.CharField(max_length = 10, null = True, blank = True, default = "-")
	girdle = models.CharField(max_length = 50, null = True, blank = True, default = "-")
	lab = models.CharField(max_length = 25, choices = LAB_CHOICES, default = "OWN")
	certno = models.CharField(max_length = 40, null = True, blank = True, default = "-")
	rap = models.FloatField(null = True, blank = True)
	price = models.FloatField(null = True, blank = True)
	image = models.ImageField(null = True, blank = True, upload_to = "images/")
	certificate = models.URLField(null = True, blank = True)
	ordered = models.BooleanField(default = False)
	video = models.URLField(null = True, blank = True, default = "")



	def __str__(self):
		return str(self.lot_no)

	@property
	def price_ct(self):
		return self.price / self.carat

	@property
	def price_total(self):
		return int(self.price*self.carat)

	@property
	def imageURL(self):
		try:
			url = self.image.url
		except:
			url = ''
		return url

	@property
	def certificateURL(self):
		try:
			url = self.certificate
		except:
			url = ''
		return url

	@property
	def videoURL(self):
		try:
			url = self.video
		except:
			url = ''
		return url

	def save(self, *args, **kwargs):
		self.pseudo_shape = self.shape
		if self.shape not in x:
			self.shape = "OTHER"
		if self.stone > 0:
			self.ordered = False
		super(Product, self).save(*args, **kwargs)


	class Meta:
   		ordering = ['lot_no']



class Order(models.Model):
	customer = models.ForeignKey(Customer, on_delete=models.CASCADE, null=True, blank=True)
	date_ordered = models.DateTimeField(auto_now_add=True)
	complete = models.BooleanField(default=False)
	transaction_id = models.CharField(max_length=100, null=True)

	def __str__(self):
		return str(self.id)
	"""
	@property
	def shipping(self):
		shipping = False
		orderitems = self.orderitem_set.all()
		for i in orderitems:
			if i.product.digital == False:
				shipping = True
		return shipping
	"""

	@property
	def shipping(self):
		return True

	@property
	def get_cart_total(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.get_total for item in orderitems])
		return total

	@property
	def get_cart_items(self):
		orderitems = self.orderitem_set.all()
		total = sum([item.quantity for item in orderitems])
		return total

class OrderItem(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
	order = models.ForeignKey(Order, on_delete=models.CASCADE, null=True)
	quantity = models.IntegerField(default=1, null=True, blank=True)
	date_added = models.DateTimeField(auto_now_add=True)

	@property
	def get_total(self):
		total = self.product.price_total * self.quantity
		return total

class ShippingAddress(models.Model):
	customer = models.OneToOneField(Customer, on_delete=models.SET_NULL, null=True)
	country = models.CharField(max_length=200, null=True, blank = True)
	state = models.CharField(max_length=100,null=True, blank = True)
	date_added = models.DateTimeField(auto_now_add=True)
	zip_code = models.CharField(max_length = 10, null = True, blank = True)

	def __str__(self):
		return str(self.date_added)


class Jewellery(models.Model):
	image = models.ImageField(null = True, blank = True, upload_to = "jewellery/")
	desc = models.TextField(null = True, blank = True)

	def __str__(self):
		return str(self.id)

	@property
	def imageURL(self):
		try:
			url = self.image.url
		except:
			url = ''
		return url

	class Meta:
		verbose_name_plural = "Jewellery"

store/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import ShippingAddress, Customer, Product, OrderItem


class LoginForm(forms.Form):
   username = forms.CharField(
       label="Username",
       widget=forms.TextInput(
           attrs={
               "class": "form-control"
           }
       ))
   password = forms.CharField(
       label="Password ",
       widget=forms.PasswordInput(
           attrs={
               "class": "form-control"
           }
       ))
    


class SignUpForm(UserCreationForm):
   username = forms.CharField(
       label="Username",
       widget=forms.TextInput(
           attrs={
               "class": "form-control"
           }
       ))
   email = forms.EmailField(
       label="Email",
       widget=forms.EmailInput(
           attrs={
               "class": "form-control"
           }
       ))
   password1 = forms.CharField(
       label="Password",
       widget=forms.PasswordInput(
           attrs={
               "class": "form-control"
           }
       ))
   password2 = forms.CharField(
       label="Re-enter your Password",
       widget=forms.PasswordInput(
           attrs={
               "class": "form-control"
           }
       ))

   class Meta:
       model = User
       fields = ('username', 'email', 'password1', 'password2')


class CustomerSignUpForm (forms.ModelForm):
  fname = forms.CharField(
      label="First Name",
      widget=forms.TextInput(
           attrs={
               "class": "form-control"
           })
    )

  lname = forms.CharField(
      label="Last Name",
      widget=forms.TextInput(
           attrs={
               "class": "form-control"
           })
    )

  company_name = forms.CharField(
      widget=forms.TextInput(
           attrs={
               "class": "form-control"
           })
    )

  mobile_no = forms.CharField(
      widget=forms.TextInput(
           attrs={
               "class": "form-control"
           })
    )

  class Meta:
    model = Customer
    fields = ('fname', 'lname', 'company_name', 'mobile_no')


class ShippingAddressForm(forms.ModelForm):
  country = forms.CharField(
      label="Country",
      widget=forms.TextInput(
           attrs={
               "class": "form-control"
           })
    )

  state = forms.CharField(
      label="State",
      widget=forms.TextInput(
           attrs={
               "class": "form-control"
           })
    )
  zip_code = forms.CharField(
      label="Zip Code",
      widget=forms.TextInput(
           attrs={
               "class": "form-control"
           })
    )

  class Meta:
    model = ShippingAddress
    exclude =['customer', ]


class ProductUpdateForm(forms.ModelForm):
  class Meta:
    model = Product
    exclude = ['', ]


class QuantityForm(forms.Form):
  quantity = forms.IntegerField()

store/templates/store/about.html
{% extends 'store/main.html' %}
{% load static %}
{% block content %}
	<script>
	$(document).ready(function(){
	  // Add smooth scrolling to all links
	  $("a").on('click', function(event) {

	    // Make sure this.hash has a value before overriding default behavior
	    if (this.hash !== "") {
	      // Prevent default anchor click behavior
	      event.preventDefault();

	      // Store hash
	      var hash = this.hash;

	      // Using jQuery's animate() method to add smooth page scroll
	      // The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area
	      $('html, body').animate({
	        scrollTop: $(hash).offset().top
	      }, 800, function(){
	   
	        // Add hash (#) to URL when done scrolling (default click behavior)
	        window.location.hash = hash;
	      });
	    } // End if
	  });
	});
	</script>
	<div id="body">
		<div class="container">
			<div id="content" class="full">
				<div class="entry text-justify">
					
					<h2>WHO WE ARE</h2>
					<div class="row">
						<div class="col-md-5">
							<!-- <img src="{% static 'images/office.jpeg' %}" class="img-fluid" style="height:600px;"> -->
							<div class="embed-responsive embed-responsive-16by9" style="height: 300px;">
								<video controls="false" class="embed-responsive-item" autoplay muted>
								  <source src="{% static 'videos/office_video.mp4' %}" type="video/mp4" />
								</video>
							</div>
							
						</div>
						<div class="col-md-7">
							<p style="font-size: 17px;">Doner Diamonds is a direct importer of quality loose diamonds longstanding relationship with established global sources of quality goods allows it to provide its clientele with exceedingly competitive margins.</p>
							<p style="font-size: 17px;">Doner Diamonds primarily supplies the wholesale industry with certified (GIA & EGL) and Non-certified (commercial) stones from its own extensive inventory of larger sized loose diamonds.</p>
							<p style="font-size: 17px;">Doner Diamonds also offers quality diamond jewelry and custom-designed pieces to the retail public. For more information about one of our finished pieces or to inquire about our own custom design, <a href = "#footer">Contact Us</a> directly to make an appointment.</p>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12 col-lg-12"><p style="font-size: 17px;">We have sold over 30,000 diamonds through our wholesale business and now are offering the same wholesale prices to you, the retailer. Feel free to contact us with any questions you may have. We are here to make your diamond purchase the most cost efficient and most pleasant experience you can have. </p>
						</div>
					</div>
					<h2>HOW WE GOT HERE</h2>

					<div class="row">
						<div class="col-md-12">
							<p style="font-size: 17px;">Doner Diamonds was first started by the Mr Ohannes Donikian when he brought his family and Diamond business over to America from Turkey in 1979. Mr Ohannes Donikian established themselves in the industry by keeping to his principles of quality, service, and expedience in everything Doner Diamonds does. Through this practice they grew the business steadily over the decades until  Arto & Kevin Donikian took over the business in the 1980's. building on everything their father bestowed upon and taught them, redefined the diamond market for consumers by being one of the few to exclusively offer and sell  (GIA & EGL) and Non-certified diamonds.</p>
							<p style="font-size: 17px;">Since then, Doner Diamonds has been an enduring strong presence in the wholesale diamond industry. Doner Diamonds is recognized as a highly experienced and professional corporation whose reputation and expertise distinguish it from others in the trade.</p>
							<p style="font-size: 17px;">Doner Diamonds has distinguished itself within the Diamond and Jewelry Market by providing a superior level of customer service and value to all of it's customers over the decades. We are always looking forward to providing you with exceptional guidance and design assistance in making any beautiful piece of jewelry and especially in designing your custom Ultimate Engagement Ring, making it truly that special symbol of your lifelong bond.</p>
							<p style="font-size: 17px;">We are not limited in the number of carats we can buy. We buy Diamonds of all kinds including Melee and other designer jewelry as well.</p>
							<p style="font-size: 17px;">Our goal is to offer you the best value for your goods and maintain a long-term relationship with you, our client.</p>
							<p style="font-size: 17px;">We want your selling experience, and our service to you, to exceed your expectations.</p>
						</div>
					</div>
					<div class="row">
						<div class="col-md-4">
						  </div>
					</div>
				</div>
				
		
			</div>
			<!-- / content -->
		</div>
		<!-- / container -->
	</div>
	<!-- / body -->
{% endblock %}

store/templates/store/accept_email.html
{% autoescape off %}
Hi {{ user.email }},
You can now search on Doner Diamonds.
{% endautoescape %}

store/templates/store/add_image_detail.html
{% extends 'store/main.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
  <div class="col-md-6 col-auto mt-2">
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group">
        {{ form | crispy }}
      </div>
      <button type="submit" class="btn btn-primary">Update</button>
    </form>
  </div>
</div>
{% endblock %}

store/templates/store/customer_email.html
<html>
<head>

</head>
<body>
	{% load static %}

<table width="100%" cellspacing="0" cellpadding="0" border="0" align="center">
	<tbody>
		<tr><td style="padding:10px">
			<table>
				<tbody>
					<tr>
						<td style="white-space:nowrap;font-family:'trebuchet ms','helvetica',sans-serif;font-size:13px" valign="top" align="left">
							<table>
								<tbody>
									<tr>
										<td valign="top" align="left">Company Name</td>
										<td valign="top" align="left">
											: {{ user.customer.company_name }}</td></tr><tr><td valign="top" align="left">Client Name
										</td>
										<td valign="top" align="left">
											: {{ user.customer.name }}
										</td>
									</tr>
									<tr>
										<td valign="top" align="left">Seller Name</td>
										<td valign="top" align="left">: Kevin</td>
									</tr>
									<tr>
										<td valign="top" align="left">Email ID</td>
										<td valign="top" align="left">
											:&nbsp;<a href="mailto:kevin@donerdiamonds.com" rel="noreferrer" target="_blank">kevin@donerdiamonds.com</a></td>
									</tr>
									<tr>
										<td valign="top" align="left">Message</td>
										<td valign="top" align="left">:</td>
									</tr>
									<tr>
										<td valign="top" align="left">Date</td>
										<td valign="top" align="left">: {{datetime}}</td>
									</tr>
									<tr>
										<td valign="top" align="left">Order By</td>
										<td valign="top" align="left">: {{ user.username }}</td>
									</tr>
									<tr>
										<td valign="top" align="left">Order No.</td>
										<td valign="top" align="left">: {{ order.id }}</td>
									</tr>
								</tbody>
							</table>
							<br>
						</td>
					</tr>
					<tr>
						<td style="white-space:nowrap;font-family:'trebuchet ms','helvetica',sans-serif;font-size:13px;padding-bottom:5px;padding-top:5px;padding-right:10px" valign="top" align="left">
							<table cellspacing="0" cellpadding="3" border="1">
								<thead>
									<tr>
										<td colspan="31" style="font-size:9pt" valign="middle" align="center">Description of Goods</td>
									</tr>
									<tr>
										<th style="font-size:9pt" valign="middle">Sr No.</th>
										<th style="font-size:9pt" valign="middle">Quantity</th>
										<th style="font-size:9pt" valign="middle">Stock No.</th>
										<th style="font-size:9pt" valign="middle">Shape</th>
										<th style="font-size:9pt" valign="middle">Carat</th>
										<th style="font-size:9pt" valign="middle">Clarity</th>
										<th style="font-size:9pt" valign="middle">Color</th>
										<th style="font-size:9pt" valign="middle">Rap%</th>
										<th style="font-size:9pt" valign="middle">Pr/Ct</th>
										<th style="font-size:9pt" valign="middle">Amount</th>
										<th style="font-size:9pt" valign="middle">Cut</th>
										<th style="font-size:9pt" valign="middle">Polish</th>
										<th style="font-size:9pt" valign="middle">Symmetry</th>
										<th style="font-size:9pt" valign="middle">Flouroscence</th>
										<th style="font-size:9pt" valign="middle">Measurement</th>
										<th style="font-size:9pt" valign="middle">Lab</th>
										<th style="font-size:9pt" valign="middle">Cert No</th>
										<th style="font-size:9pt" valign="middle">Dept</th>
										<th style="font-size:9pt" valign="middle">Location</th>
										<th style="font-size:9pt" valign="middle">ShowId</th>
									</tr>
								</thead>
								<tbody>
									<tr></tr>
									{% for orderitem in order.orderitem_set.all %}
									<tr>
										<td style="font-size:9pt" valign="middle" align="center">{{ forloop.counter }}</td>
										<td style="font-size:9pt" valign="middle" align="center">{{ orderitem.quantity }}</td>
										<td style="font-size:9pt" valign="middle" align="center">{{ orderitem.product.lot_no }}</td>
										<td style="font-size:9pt" valign="middle" align="center">{{ orderitem.product.get_shape_display }}</td>
										<td style="font-size:9pt" valign="middle" align="center">{{ orderitem.product.carat }}</td>
										<td style="font-size:9pt" valign="middle" align="center">{{ orderitem.product.get_clarity_display }}</td>
										<td style="font-size:9pt" valign="middle" align="center">{{ orderitem.product.get_color_display }}</td>
										<td style="font-size:9pt" valign="middle" align="center">{{ orderitem.product.rap }}</td>
										<td style="font-size:9pt" valign="middle" align="center">{{ orderitem.product.price_ct }}</td>
										<td style="font-size:9pt" valign="middle" align="center">{{ orderitem.product.price }}  {{ orderitem.quantity }} </td>
										<td style="font-size:9pt" valign="middle" align="center">{{ orderitem.product.cut }}</td>
										<td style="font-size:9pt" valign="middle" align="center">{{ orderitem.product.pol }}</td>
										<td style="font-size:9pt" valign="middle" align="center">{{ orderitem.product.sym }}</td>
										<td style="font-size:9pt" valign="middle" align="center">{{ orderitem.product.fl }}</td>
										<td style="font-size:9pt" valign="middle" align="center">{{ orderitem.product.measurement }}</td>
										<td style="font-size:9pt" valign="middle" align="center">{{ orderitem.product.lab }}</td>
										<td style="font-size:9pt" valign="middle" align="center">{{ orderitem.product.certno }}</td>
										<td style="font-size:9pt" valign="middle" align="center">{{ orderitem.product.dept }}</td>
										<td style="font-size:9pt" valign="middle" align="center">{{ orderitem.product.dept }}</td>
										<td style="font-size:9pt" valign="middle" align="center">{{ orderitem.product.dept }}</td>
										<td style="font-size:9pt" valign="middle" align="center"></td>
									</tr>
									{% endfor %}
								</tbody>
								<tfoot>
									<tr>
										<td colspan="2" style="font-size:9pt" valign="middle" align="left"></td>
										<td style="font-size:9pt" valign="middle" align="right">Total Carats</td>
										<td style="font-size:9pt" valign="middle" align="center">{{ totalcarat }}</td>
										<td colspan="4" style="font-size:9pt" valign="middle" align="right"></td>
										<td colspan="2" style="font-size:9pt" valign="middle" align="right">Shipping Charges</td>
										<td style="font-size:9pt" valign="middle" align="center"> {{shipping_charges}} </td>
										<td colspan="20" style="font-size:9pt" valign="middle" align="right"></td>
									</tr>
									<tr>
										<td colspan="8" style="font-size:9pt" valign="middle" align="left"></td>
										<td colspan="2" style="font-size:9pt" valign="middle" align="right">Grand Total</td>
										<td style="font-size:9pt" valign="middle" align="center">{{ grandtotal }}</td>
										<td colspan="20" style="font-size:9pt" valign="middle" align="right"></td>
									</tr>
								</tfoot>
							</table>
						</td>
					</tr>
					<tr>
						<td style="white-space:nowrap;font-family:'trebuchet ms','helvetica',sans-serif;font-size:13px;padding-top:5px" valign="top" align="left">
							Thank you for placing the order through <a href="www.donerdiamonds.com"> Doner Diamonds</a>&nbsp;Website.
						</td>
					</tr>
					<tr>
						<td style="white-space:nowrap;font-family:'trebuchet ms','helvetica',sans-serif;font-style:italic;font-size:13px;padding-top:5px" valign="top" align="left">
							Please click here for T&amp;C.
						</td>
					</tr>
					<tr>
						<td style="white-space:nowrap;font-family:'trebuchet ms','helvetica',sans-serif;font-size:13px;padding-bottom:5px;padding-top:10px" valign="top" align="left">
							Yours Sincerely,<br>DD Team
						</td>
					</tr>
					
				</tbody>
			</table>
		</td>
	</tr>
</tbody>
</table>

</body>
</html>

store/templates/store/product.html
{% extends 'store/main.html' %}
{% block content %}
	<div id="body">
		<div class="container">
			<div id="content" class="full">
				<div class="product">
					<div class="image">
						<img src="{{ product.imageURL }}" alt="">
					</div>
					<div class="details">
						<h1>{{ product.lot_no }}</h1>
						<h4>${{ product.price_total }}</h4>
						<div class="entry">

							<div class="tabs">
								<div class="nav">
									<ul>
										<li class = "active" style="padding-left: 10px;padding-right: 45px;"><a href="#spec">Specification</a></li>
										<li><a href="#ret">Certificate</a></li>
										<li><a href="#vid">Video</a></li>
									</ul>
								</div>
								<div class="tab-content active" id="spec">
									<p><b>Shape: </b>{{ product.get_pseudo_shape_display }}</p>
									<p><b>Clarity: </b>{{ product.get_clarity_display }}</p>
									<p><b>Color: </b>{{ product.get_color_display }}</p>
									<p><b>Carat: </b>{{ product.carat}}</p>
									<p><b>Stone: </b>{{ product.stone}}</p>
									<p><b>Measurement: </b>{{ product.measurement }}</p>
									<p><b>Dept: </b>{{ product.dept }}</p>
									<p><b>TBL: </b>{{ product.tbl }}</p>
									<p><b>Cut: </b>{{ product.cut }}</p>
									<p><b>Pol: </b>{{ product.Pol }}</p>
									<p><b>Sym: </b>{{ product.sym }}</p>
									<p><b>FL: </b>{{ product.fl }}</p>
									<p><b>CUL: </b>{{ product.cul }}</p>
									<p><b>Girdle: </b>{{ product.girdle }}</p>
									<p><b>Lab: </b>{{ product.lab }}</p>
									<p><b>Certificate No.: </b>{{ product.certno }}</p>
									<p><b>Rap: </b>{{ product.rap }}</p>
								</div>
								<div class="tab-content" id="ret">

										<img src="{{ product.certificateURL }}" alt="">

								</div>
								<div class="tab-content" id="vid">

										<img src="{{ product.videoURL }}" alt="">

								</div>
							</div>
						</div>

						<div class="actions">
								<a type="submit" class="btn-grey" href = "{% url 'add-product' product.pk %}">Add to Cart</a>

						</div>
					</div>
				</div>
			</div>
			<!-- / content -->
		</div>
		<!-- / container -->
	</div>
	<!-- / body -->
{% endblock content %}